{{- if .Values.worker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "factorial-service.fullname" . }}-worker
  labels:
    app: {{ include "factorial-service.name" . }}
    component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "factorial-service.fullname" . }}-worker
  minReplicas: {{ .Values.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.worker.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

{{- if .Values.calculator.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "factorial-service.fullname" . }}-calculator
  labels:
    app: {{ include "factorial-service.name" . }}
    component: calculator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "factorial-service.fullname" . }}-calculator
  minReplicas: {{ .Values.calculator.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.calculator.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.calculator.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}

