apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorial-service.fullname" . }}-secret
type: Opaque
data:
  db-password: {{ "password" | b64enc | quote }}
  rabbitmq-password: {{ "guest" | b64enc | quote }}
  redis-password: {{ "" | b64enc | quote }}

