apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorial-service.fullname" . }}-worker
  labels:
    app: {{ include "factorial-service.name" . }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "factorial-service.name" . }}
      component: worker
  template:
    metadata:
      labels:
        app: {{ include "factorial-service.name" . }}
        component: worker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        env:
        - name: DB_USER
          value: {{ .Values.database.user }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "factorial-service.fullname" . }}-secret
              key: db-password
        - name: DB_HOST
          value: {{ .Values.database.host }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_NAME
          value: {{ .Values.database.name }}
        - name: DB_SSLMODE
          value: {{ .Values.database.sslmode }}
        - name: RABBITMQ_USER
          value: {{ .Values.rabbitmq.user }}
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "factorial-service.fullname" . }}-secret
              key: rabbitmq-password
        - name: RABBITMQ_HOST
          value: {{ .Values.rabbitmq.host }}
        - name: RABBITMQ_PORT
          value: {{ .Values.rabbitmq.port | quote }}
        - name: FACTORIAL_CAL_SERVICES_QUEUE_NAME
          value: {{ .Values.config.queueName }}
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "factorial-service.fullname" . }}-secret
              key: redis-password
        - name: REDIS_DB
          value: {{ .Values.redis.db | quote }}
        - name: AWS_REGION
          value: {{ .Values.aws.region }}
        - name: S3_BUCKET_NAME
          value: {{ .Values.aws.s3Bucket }}
        - name: MAX_FACTORIAL
          value: {{ .Values.config.maxFactorial | quote }}
        - name: REDIS_THRESHOLD
          value: {{ .Values.config.redisThreshold | quote }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}

