name: App API deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # 0. Set up Go (for building binaries)
      - name: Log info
        run: |
            echo "${{ vars.AWS_GITHUB_ACTION_ROLE  }}"
            echo "${{ vars.AWS_REGION  }}"
            echo "${{ vars.ECR_REGISTRY  }}"
            echo "${{ vars.ECR_REPOSITORY  }}"
            echo "${{ vars.ECR_REPOSITORY_WORKER  }}"
            echo "${{ vars.ECS_CLUSTER  }}"
            echo "${{ vars.ECS_SERVICE  }}"
            echo "${{ vars.ECS_TASK_DEFINITION  }}"
            echo "${{ vars.TASK_DEFINITION_ARN_API  }}"
            echo "${{ vars.TASK_DEFINITION_ARN_WORKER  }}"

      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4


      # 3. Set up Go (for building binaries)
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      # 4. Install dependencies
      - name: Install dependencies
        run: go mod download

      # 5. Install swag for generating Swagger docs
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      # 6. Generate Swagger documentation
      - name: Generate Swagger docs
        run: swag init -g cmd/api/main.go -o docs

      # 7. Run tests
      - name: Run tests
        run: go test -v ./tests -race -timeout 300s -cover

      # 8. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTION_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      # 9. Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 10. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      # 11. Build and push APP image
      - name: Build and push APP image
        id: build-app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CMD_PATH=./cmd/api/main.go

      - name: Deploy to ECS Fargate
        run: |

          echo "Cập nhật Service với Task Definition mới..."
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --service ${{ vars.ECS_SERVICE }} \
            --task-definition ${{ vars.TASK_DEFINITION_ARN_API }} \
            --force-new-deployment

          SERVICE_ARN=$(aws ecs describe-services \
              --cluster ${{ vars.ECS_CLUSTER }} \
              --services ${{ vars.ECS_SERVICE }} \
              --query 'services[0].serviceArn' \
              --output text)

          echo "Đang chờ Service ổn định (Timeout sau 10 phút)..."

          if ! aws ecs wait services-stable \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --services $SERVICE_ARN; then
              
              echo "::error::Deployment đã thất bại hoặc timeout. Đang tìm lý do dừng task."
              
              STOPPED_TASK=$(aws ecs list-tasks \
                --cluster ${{ vars.ECS_CLUSTER }} \
                --service-name ${{ vars.ECS_SERVICE }} \
                --desired-status STOPPED \
                --query 'taskArns[0]' \
                --output text)

              if [ "$STOPPED_TASK" != "None" ]; then
                  aws ecs describe-tasks \
                    --cluster ${{ vars.ECS_CLUSTER }} \
                    --tasks $STOPPED_TASK \
                    --query 'tasks[0].stoppedReason' \
                    --output text
              fi
              
              exit 1
          fi

          echo "Deployment hoàn tất và Service ổn định. ✅"
