name: Deploy worker service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # 0. Set up Go (for building binaries)
      - name: Log info
        run: |
            echo "${{ vars.AWS_GITHUB_ACTION_ROLE  }}"
            echo "${{ vars.AWS_REGION  }}"
            echo "${{ vars.ECR_REGISTRY  }}"
            echo "${{ vars.ECR_REPOSITORY  }}"
            echo "${{ vars.ECR_REPOSITORY_WORKER  }}"
            echo "${{ vars.ECS_CLUSTER  }}"
            echo "${{ vars.ECS_SERVICE  }}"
            echo "${{ vars.ECS_SERVICE_WORKER  }}"
            echo "${{ vars.ECS_TASK_DEFINITION  }}"
            echo "${{ vars.TASK_DEFINITION_ARN_API  }}"
            echo "${{ vars.TASK_DEFINITION_ARN_WORKER  }}"

      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4


      # 3. Set up Go (for building binaries)
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      # 4. Install dependencies
      - name: Install dependencies
        run: go mod download

      # 5. Run tests
      - name: Run tests
        run: go test -v ./tests -race -timeout 300s -cover

              # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTION_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      # 7. Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest


      # 9. Build and push WORKER image
      - name: Build and push WORKER image
        id: build-worker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.worker
          push: true
          tags: |
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY_WORKER }}:${{ github.sha }}
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY_WORKER }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CMD_PATH=./cmd/worker/main.go

      # 12. Update ECS task definition for WORKER
      - name: Deploy to ECS Fargate
        run: |


          echo "Cập nhật Service với Task Definition mới..."
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER  }} \
            --service ${{ vars.ECS_SERVICE_WORKER  }} \
            --task-definition ${{ vars.TASK_DEFINITION_ARN_WORKER }} \
            --force-new-deployment

          SERVICE_ARN=$(aws ecs describe-services \
              --cluster ${{ vars.ECS_CLUSTER  }} \
              --services ${{ vars.ECS_SERVICE_WORKER  }} \
              --query 'services[0].serviceArn' \
              --output text)

          echo "Đang chờ Service ổn định (Timeout sau 10 phút)..."

          # 2. Chờ cho đến khi Service stable.
          # Nếu lệnh này thất bại (do timeout), script sẽ dừng ngay lập tức
          if ! aws ecs wait services-stable \
            --cluster ${{ vars.ECS_CLUSTER  }} \
            --services $SERVICE_ARN; then
            
            echo "::error::Deployment đã thất bại hoặc timeout. Đang tìm lý do dừng task."
            
            # Lệnh bổ sung để lấy lý do dừng của task gần nhất
            # (Chỉ lấy 1 task bị dừng gần nhất)
            STOPPED_REASON=$(aws ecs list-tasks \
              --cluster ${{ vars.ECS_CLUSTER  }} \
              --service-name ${{ vars.ECS_SERVICE_WORKER  }} \
              --desired-status STOPPED \
              --query 'taskArns[0]' \
              --output text)

            if [ "$STOPPED_REASON" != "None" ]; then
                aws ecs describe-tasks \
                  --cluster ${{ vars.ECS_CLUSTER  }} \
                  --tasks $STOPPED_REASON \
                  --query 'tasks[0].stoppedReason' \
                  --output text
            fi
            
            # Thoát với mã lỗi để fail workflow
            exit 1
          fi

          echo "Deployment hoàn tất và Service ổn định. ✅"
          